### ISSUE TITLE
[Epic] AT / CI improvements

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1425]
## Description of the Epic

Improving AT / CI by updating the automated (AT) and visual regression testing (VRT) tooling and streamlining the reporting of results.

General thoughts: Every PR should pass AT.  Some PRs need to pass VRT.

Tooling updates:
- https://open-wc.org/docs/testing/testing-package/

## Related issues

- [ ] https://github.com/patternfly/patternfly-elements/issues/1350: Visual regression testing challenges
- [x] https://github.com/patternfly/patternfly-elements/issues/1408: Using test-fixtures + React & Vue
- [x] https://github.com/patternfly/patternfly-elements/issues/1256: Remove the build from the test command
- [x] https://github.com/patternfly/patternfly-elements/issues/386: Release action (probably out-of-scope)

## Proof of concept PRs that might be useful
- Docker: https://github.com/patternfly/patternfly-elements/pull/1401
- Percy PoC: https://github.com/patternfly/patternfly-elements/pull/1267
- E2E PoC: https://github.com/patternfly/patternfly-elements/pull/1058

## Related GitHub Actions
- https://github.com/marketplace/actions/percy

**Comment by castastrophe** [comment]
Personally, I updated to Big Sur and found that the wct no longer works locally because selenium-standalone-server no longer has the permissions it needs to spin up.  A docker instance or updating of the test tool would allow me to run AT locally again.

**Comment by castastrophe** [comment]
From issue #1519: `Justin recommended Web Test Runner very highly. We should investigate and see how much effort it would be to incorporate.`
