### ISSUE TITLE
[meta]: Migrate Components to Lit

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#1797]
## Components

- [ ] `<pfe-accordion>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-autocomplete>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-avatar>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-badge>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-band>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-button>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-card>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-clipboard>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-codeblock>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-collapse>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-content-set>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-cta>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-datetime>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-dropdown>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-health-index>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-icon-panel>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-icon>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-jump-links>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-markdown>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-modal>`
    - [x] Code
    - [x] Tests
    - [ ] e2e

- [ ] `<pfe-navigation>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-number>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-page-status>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-primary-detail>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-progress-indicator>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-progress-steps>`
    - [x] Code
    - [x] Tests
    - [x] e2e

- [ ] `<pfe-readtime>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-select>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-styles>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-tabs>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

- [ ] `<pfe-toast>`
    - [ ] Code
    - [ ] Tests
    - [ ] e2e

## Questions
Can we use decorators? Or in otherwords, can we either depend on `tslib` or bundle inline ts helpers?

**Comment by bennypowers** [comment]
cc @kylebuch8 @mwcz

**Comment by bennypowers** [comment]
This is done :D
