### ISSUE TITLE
Official pfe-accordion status

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#489]
- [x] schema
- [x] theme support
- [x] framework support
    - [x] Angular
    - [x] React
    - [x] Vue
- [x] no major outstanding bugs
    - [T5 FED Rally story will review & test these PRs](https://rally1.rallydev.com/#/270861059696d/detail/userstory/298694337308)
        - [x] pfe-accordion | Fix collapse animation #429 
        - [x] pfe-accordion | resolves accessibility issue #444  

    - Add in pfe-collapsible @kylebuch8 this needs a PR

**Comment by starryeyez024** [comment]
- [ ] pfe-accordion | Fix collapse animation #429 
- [ ] pfe-accordion | resolves accessibility issue #444  
- [ ] pfe-accordion: Enhancements and code refactor #469
