### ISSUE TITLE
Official Documentation

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#501]
- [ ] Add link to design kit repo from https://www.patternfly.org/v4/design-guidelines/styles/colors
- [ ] Add links to current PatternFly Elements storybook demos to the design repo
- [ ] Add documentation to the design kit repo noting which elements should be modified in which order (check storybook attributes)
- [x] Look at enhancing PatternLab / Storybook to be more intuitive for designers to pick up Attribute Settings (storybook), Theme Variables (repo theme SASS), CSS Variables as Design Options
- [ ] Ensure each markdown file & storybook examples use correct variants
    - i.e. pfe-card: storybook still says color= instead of pfe-color, the markdown file doesn't list the overflow variants 

https://github.com/patternfly/patternfly-unified-design-kit/issues/57#issuecomment-521746080
